services:
  ffmpeg:
    image: ghcr.io/technotut/srt-relay-server:main
    container_name: ffmpeg
    ports:
     - "2000:2000/udp"
     - "3000:3000/udp"
    restart: unless-stopped
    environment:
     - RECEIVE_PORT=2000
     - SEND_PORT=3000
    secrets:
      - passphrase
secrets: 
  passphrase:
    file: .passphrase
