apiVersion: v1
kind: Service
metadata:
  name: srt-relay-service
  labels:
    app: srt-relay-server
  namespace: srt
spec:
  selector:
    app: srt-relay-server
  type: NodePort
  ports:
    - name: srt-receive
      protocol: UDP
      port: 2000
      targetPort: 2000
      nodePort: 30200
    - name: srt-send
      protocol: UDP
      port: 3000
      targetPort: 3000
      nodePort: 30300